### PR TITLE
Respect update serial in bosh manifest

### LINKED ISSUE #636: Respect update.serial setting of BOSHDeployment
Currently all Instance Groups are starting in parallel. For [scf](https://github.com/SUSE/scf), this will produce a lot of container crashes (e.g. api needs uaa running). This increases the boot times, because every crash doubles the time until the next restart takes place.

The boot time could be reduced by respecting the `update.serial` setting in the Manifest.
We did some experiments with  [scf](https://github.com/SUSE/scf)

|          | Serial Boot   | Parallel Boot |
|--------|----------------|---------------|
| Time |  Between 14 and 16 min | Between 20 and 30 minutes|
| Crashes | No crashes               |  Many crashes |

We implemented this with the help of an additional init container, which was running before `boshPreStartInitContainers` and waits until `nslookup` of the headless service of the previous instance group was not failing. (For details have a look at our [branch based on 0.4.0 ](https://github.com/akhinos/cf-operator/tree/poc-init-order))

### PR DESCRIPTION
**Pull request by c0d1ngm0nk3y**
Fixes #636 

This introduces an initContainer waiting for another instance group to be reachable via service if the `update: serial` is set accordingly in the manifest.

This results in faster startup times since there are fewer crashes and `CrashLoopBackOff`s. Also the startup phase looks a bit smoother.

There are still some crashes left (e.g. one container of `api` crashes if the database is not migrated yet, this is done by another container)

There is a special handling of the eirini instance group inside `manifest.go`, because eirini is patched at the wrong position inside the manifest. We will prepare a PR for scf to fix this (https://github.com/SUSE/scf/pull/2980). Afterward, this special handling can be removed.

We tried to write an e2e test. But we had several problems to run e2e tests with multiple instance groups (#645 ).

### CODE REVIEW

**Comment by loewenstein** [comment]
> There are still some crashes left (e.g. one container of api crashes if the database is not migrated yet, this is done by another container)

I suppose this will be handled in https://github.com/SUSE/scf/issues/2975

**Comment by c0d1ngm0nk3y** [comment]
> > There are still some crashes left (e.g. one container of api crashes if the database is not migrated yet, this is done by another container)
> 
> I suppose this will be handled in [SUSE/scf#2975](https://github.com/SUSE/scf/issues/2975)

I think this is another issue, because this focuses on uaa (I assume).

We have at least 3 types of crashes left
1) One container of `api` crashes because another container did not migrate the database yet
2) `cc-worker` crashes because the database is not migrated yet. But `cc-worker` has no `update: serial`, so I wonder how this works in `BOSH`
3) Even *WITH* the database migrated `api` crashes, but "only" 2 times or so.

**Comment by jpalmerLinuxFoundation** [comment]
Hi Team, 
EasyCLA check indicates all authors are covered by a signed CLA.
image
Current functionality does not update the initial failure comment (CLA Not Signed) when check passes subsequently.  This was done to reduce comments made to PRs, but we're working on a change to update the comment if one exists on the PR.
https://github.com/communitybridge/easycla/issues/269

**Comment by c0d1ngm0nk3y** [comment]
@f0rmiga @manno Could you have a look? Any comments?

**Comment by kramerul** [comment]
I reopened https://github.com/SUSE/scf/pull/2980 as https://github.com/SUSE/kubecf/pull/60

**Comment by c0d1ngm0nk3y** [comment]
It would be great to get this merged for 3 reasons

1) It shortens the startup times - mainly because there are less `CrashLoopBackOff`
2) It brings some order to the startup removes some race conditions - see https://github.com/SUSE/kubecf/issues/3
3) The startup  looks  much smoother without many crashes that are "normal" because some pod is not ready yet.

Is there any downside?

**Comment by viovanov** [comment]
@c0d1ngm0nk3y we haven't been able to review this yet, it will probably happen next week

**Comment by c0d1ngm0nk3y** [comment]
> @c0d1ngm0nk3y we haven't been able to review this yet, it will probably happen next week

It would be great to get some feedback on this to get this hopefully merged soon. The fewer `CrashLoopBackOff`s would be great to have imho.

**Comment by kramerul** [comment]
> Hi,
> Would love to see that, but I'm focusing on #663 and would prefer that one first. However conflicts are minimal.
> 
> Could you squash the commits a little?
> I'm going to ask around in our daily about the manifest name, I don't think we need `LoadYAMLByName` as we enforce the name to be the BDPL resource name.

The enforcement is done at a later point in time (I think after one serialise/deserialise cycle). For this PR, we need the correct name immediately.

File: pkg/bosh/converter/resolver.go [hunk 1]
```diff
@@ -106,8 +106,9 @@ func (r *ResolverImpl) WithOpsManifest(ctx context.Context, instance *bdv1.BOSHD
 		}
 	}
 
+	instanceName := instance.GetName()
```
Comment (manno) [inline pkg/bosh/converter/resolver.go]: Took me a while to figure out `instance` is actually a bdpl resource :)

File: pkg/bosh/manifest/instance_group.go [hunk 2]
```diff
@@ -25,22 +27,72 @@ func (instanceGroups InstanceGroups) InstanceGroupByName(name string) (*Instance
...
+	Env                AgentEnv                `json:"env,omitempty"`
+}
+
+// InstanceGroupQuarks represents the quark property of a InstanceGroup
+type InstanceGroupQuarks struct {
+	RequiredService *string `json:"required_service,omitempty"`
+}
+
+// InstanceGroupProperties represents the properties map of a InstanceGroup
+type InstanceGroupProperties struct {
```
Comment (manno) [inline pkg/bosh/manifest/instance_group.go]: Can this be solved like this https://github.com/cloudfoundry-incubator/cf-operator/blob/master/pkg/bosh/manifest/job.go#L63-L66

I kind of remember that we don't need the JSON workaround with `sigs.k8s.io/yaml`.

**Comment by manno** [comment]
We moved this PR upwards in the backlog: https://www.pivotaltracker.com/n/projects/2192232

File: pkg/bosh/manifest/manifest.go [hunk 3]
```diff
@@ -158,6 +158,11 @@ type duplicateYamlValue struct {
 
 // LoadYAML returns a new BOSH deployment manifest from a yaml representation
 func LoadYAML(data []byte) (*Manifest, error) {
+	return LoadYAMLWithName(data, nil)
+}
+
+// LoadYAMLWithName returns a new BOSH deployment manifest from a yaml representation with the given name
+func LoadYAMLWithName(data []byte, name *string) (*Manifest, error) {
```
Comment (viovanov) [inline pkg/bosh/manifest/manifest.go]: This should be set as soon as possible, and should already be set in the desired manifest.
Do you need it _before_ the desired manifest is a thing?

Comment (kramerul) [reply pkg/bosh/manifest/manifest.go]: We started without this change. But it turned out that we got the wrong service names (DNS entries) to wait for.

File: pkg/bosh/manifest/manifest.go [hunk 4]
```diff
@@ -192,6 +200,46 @@ func (m *Manifest) loadDNS() error {
...
+		}
+		if ig.Update != nil && ig.Update.Serial != nil {
+			serial = *ig.Update.Serial
+		}
+
+		//FIXME This is required because eirini is inserted as last instance group in https://github.com/SUSE/scf
+		// Without this condition, eirini would wait for all other instance groups. On the other hand, there are
+		// instance groups, which require eirini. Therefore, without this condition there will be a deadlock
+		// This can be removed, if the position of eirini in scf is fixed.
+		if strings.Contains(ig.Name, "eirini") {
```
[the remark this answers is not in the document]
Comment (kramerul) [reply pkg/bosh/manifest/manifest.go]: I removed this special handling for eirini.

File: pkg/bosh/manifest/manifest.go (hunk 3 above)
Comment (kramerul) [reply pkg/bosh/manifest/manifest.go]: You can see it also in the changed test `resolver_test.go`, that the name of the loaded  manifest was not correct. 
It was quite confusing for us, that the name was not correct when the manifest is loaded the first time.

Comment (manno) [reply pkg/bosh/manifest/manifest.go]: Historically we assumed the bdpl name would be equal to the manifest name. I think we discussed to add a check for that, but must have somehow ended up with the enforcement in `deployment_reconciler.go`.

The behavior/expectation is also documented, at least in once place: https://github.com/cloudfoundry-incubator/cf-operator/blame/master/docs/from_bosh_to_kube.md#L60

That's also the problem with the [resolver_test.go](https://github.com/cloudfoundry-incubator/cf-operator/blob/5c7bb82f371627cf92516d321ab26c4b314b95f3/pkg/bosh/converter/resolver_test.go#L136), the test data is 'wrong'.

I'm not sure we have the best approach here, convention and partial enforcement. Maybe it makes sense to ignore the bdpl name and use the manifest name everywhere. Syncing these two values everywhere in the code seems brittle, as you discovered ;)

However, I'd rather have the  clean up in a proper story so we have a consistent approach to this design issue?

File: cmd/internal/wait.go [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+func init() {
+	rootCmd.AddCommand(waitCmd)
+}
+
+var waitCmd = &cobra.Command{
+	Use:   "wait",
+	Short: "Wait for required service",
+	Args:  cobra.ExactArgs(1),
+	Run: func(cmd *cobra.Command, args []string) {
+		for {
```
[the remark this answers is not in the document]
Comment (c0d1ngm0nk3y) [reply cmd/internal/wait.go]: We can add this of course, bur I would like to understand the reasoning/benefit. This would result in crashing the container, right? And this is one thing this `PR` is  addressing. We  could  of course set the default to `0`, but for what do we need it then?

[the remark this answers is not in the document]
Comment (f0rmiga) [reply cmd/internal/wait.go]: We don't want to avoid it to crash at all costs. I think crashing the init container after a sensible timeout is reached is useful for telling us that something bad happened, instead of waiting forever.

File: pkg/bosh/manifest/manifest.go (hunk 3 above)
Comment (c0d1ngm0nk3y) [reply pkg/bosh/manifest/manifest.go]: > How about we always use the bdpl name, and we don't even [de]serialize the name?
> Then you **always** have to provide the name when you call LoadYaml, and you can error if it's empty.

You mean in a separate story/PR, right?

File: cmd/internal/wait.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (c0d1ngm0nk3y) [reply cmd/internal/wait.go]: We have added a timeout. But I would argue that a bit more determinism would help the cf-operator a lot. Why crash and just try it again. If it works, errors could be hidden. But the timeout should not hurt for sure.

File: cmd/internal/wait.go [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+	"time"
+
+	"github.com/spf13/cobra"
+)
+
+func init() {
+	rootCmd.AddCommand(waitCmd)
+}
+
+var waitCmd = &cobra.Command{
```
[the remark this answers is not in the document]
Comment (c0d1ngm0nk3y) [reply cmd/internal/wait.go]: Done

File: pkg/bosh/manifest/manifest.go (hunk 3 above)
Comment (manno) [reply pkg/bosh/manifest/manifest.go]: Seems complicated to do, e.g. the `variable-interpolation` command takes a file name and doesn't know the name of the bdpl resource.

File: cmd/internal/wait.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (f0rmiga) [reply cmd/internal/wait.go]: I think the main advantage of having the timeout is that it tells us that something went wrong rather than never telling us anything.

[the remark this answers is not in the document]
Comment (c0d1ngm0nk3y) [reply cmd/internal/wait.go]: Debatable :) If it doesn't start at all, you would notice. I would agree if it would not just  be restarted. I am not a big fan of "eventually consistent". We see it from time to time that the `cf-operator` behaves strange (e.g. not creating `StatefulSets` for 1 hour), but  if we keep the system running long enough it turn out to be up and  running.
Which has of course also a good side to it, but I wonder sometime how  indeterministic the `cf-operator` can be.

**Comment by c0d1ngm0nk3y** [comment]
> `cmd/cf-operator/cf-operator` binary file is added in one of the commits. You will need to interactively rebase the commits and edit the commit that introduced it, otherwise, it will pollute master once we merge.

Good catch. I will have a look.

File: pkg/bosh/manifest/manifest.go (hunk 3 above)
Comment (c0d1ngm0nk3y) [reply pkg/bosh/manifest/manifest.go]: Should this block this PR? Or is something else missing? It seems that this is not directly  related to this PR, right?

Comment (viovanov) [reply pkg/bosh/manifest/manifest.go]: @c0d1ngm0nk3y you added this function to the package, and I don't think it makes sense.
As a developer, I don't know why that package is exposing these 2 functions and what the differences are. We can create another story, but I thought my suggestion would be fast to implement.
If you don't think so, please let me know.

Comment (loewenstein) [reply pkg/bosh/manifest/manifest.go]: @viovanov quoting @manno 
> Seems complicated to do, e.g. the variable-interpolation command takes a file name and doesn't know the name of the bdpl resource.

It seems not to be straight forward. I'd propose to merge this and create a chore to clean up the use of manifest and deployment names. WDYT?

Comment (c0d1ngm0nk3y) [reply pkg/bosh/manifest/manifest.go]: @viovanov I agree that a 2nd `LoadYaml` is confusing and for sure not what we want in the end. But I  think the existing `LoadYaml` is kind of buggy  since it returns different outcomes depending on when it is called. But `LoadYaml` is called quite often, so we didn't want to change this without  understanding the consequences in depth. I think it is an existing bug and not directly  related to this PR, but we can have a look. I was just a bit careful because of the "Seems complicated to do" @manno

Comment (viovanov) [reply pkg/bosh/manifest/manifest.go]: Fair enough - we could merge and schedule something else. This has been open for a while.

Comment (viovanov) [reply pkg/bosh/manifest/manifest.go]: https://www.pivotaltracker.com/story/show/169575453

Comment (c0d1ngm0nk3y) [reply pkg/bosh/manifest/manifest.go]: Yes, it's been a while and I am keen of getting this in. So, please let me know when you see something that should be addressed/clarified :)

@manno Could you perhaps clarify which change you would like to see to get this merged?

Comment (manno) [reply pkg/bosh/manifest/manifest.go]: @c0d1ngm0nk3y @loewenstein 
Please focus this PR on the update serial behavior, changing the `LoadYAML` is another discussion and should be a separate story.

I still think you should remove the new `LoadYAMLWithName` from this PR, if you fix the test data I [pointed to earlier](https://github.com/cloudfoundry-incubator/cf-operator/blob/5c7bb82f371627cf92516d321ab26c4b314b95f3/pkg/bosh/converter/resolver_test.go#L136).

**Comment by kramerul** [comment]
@viovanov,

simply reverting our change in LoadYAML will not work. 
Our feature only works, if you don't change the corresponding unit tests!
The problem is that the service names will be wrong.

**Comment by manno** [comment]
> @viovanov,
> 
> simply reverting our change in LoadYAML will not work.
> Our feature only works, if you don't change the corresponding unit tests!
> The problem is that the service names will be wrong.

I think that's because existing test data didn't care about our 'convention'. Let me try to clean that up.

**Comment by c0d1ngm0nk3y** [comment]
> e60f266



> I think that's because existing test data didn't care about our 'convention'.

@manno By 'convention' you mean that `bdpl name == manifest name`? At  least 3 weeks ago, this was not true for `kubecf`/`scf`. So the code constructed the wrong service names (e.g. `cf-database` instead of `scf-database`.

3 weeks ago, this was definitely  a bug imho. The manifest name was later changed, but too late depending on when you call it. If the 2 should be the same, why synch them at all?

@viovanov Maybe, `kubecf` or `cf-operator` changed in the meantime, so that this is no longer needed. But it was needed when we opened the  PR. Most pods waited for non existing services. So we  should test it with the latest `kubecf`.

**Comment by viovanov** [comment]
@c0d1ngm0nk3y yes, I think I remember that - it was a bug in kubecf.
I think fixing the test is ok for this PR, we can merge, and afterwards we can properly fix this code in https://www.pivotaltracker.com/story/show/169575453

Sorry this took so long 😅

**Comment by manno** [comment]
I tried to fix all the places, so this doesn't turn into a game of whack-a-mole...

https://github.com/cloudfoundry-incubator/cf-operator/commit/8d4635f7f8252b41805ea26ae60d187369cf79c1

**Comment by c0d1ngm0nk3y** [comment]
> I think I remember that - it was a bug in kubecf.

I think you are refering to a different bug. For `kubecf` it is normal that the manifest name (*cf*) is different from the name o the bdpl (*kubecf*), isn't it???

I had my doubts  that this still works after reverting this part and tested installing `kubecf` and nearly no  pod is getting ready because the pods are waiting for a service `cf-xxx` instead of `kubecf-xxx`.
So for `kubecf`, the "convention" that manifest name = bdpl name is still not true. But `kubecf` is the main reason for `cf-operator`, right?

*Summary* `kubecf` cannot be installed with the master of `cf-operator` after this modified PR.
@kramerul , @viovanov , @manno I would suggest we re-add the missing code on Monday to make it work again and figure then out how to continue.
